const COUNTRY_FLAGS: Record<string, string> = {
  Polska: "🇵🇱",
  Poland: "🇵🇱",
  poland: "🇵🇱",
  "Stany Zjednoczone": "🇺🇸",
  "United States": "🇺🇸",
  USA: "🇺🇸",
  US: "🇺🇸",
  us: "🇺🇸",
  "United States of America": "🇺🇸",
  "Wielka Brytania": "🇬🇧",
  "United Kingdom": "🇬🇧",
  UK: "🇬🇧",
  uk: "🇬🇧",
  Niemcy: "🇩🇪",
  Germany: "🇩🇪",
  Francja: "🇫🇷",
  France: "🇫🇷",
  Włochy: "🇮🇹",
  Italy: "🇮🇹",
  Hiszpania: "🇪🇸",
  Spain: "🇪🇸",
  Holandia: "🇳🇱",
  Netherlands: "🇳🇱",
  Belgia: "🇧🇪",
  Belgium: "🇧🇪",
  Szwajcaria: "🇨🇭",
  Switzerland: "🇨🇭",
  Austria: "🇦🇹",
  Czechy: "🇨🇿",
  "Czech Republic": "🇨🇿",
  Szwecja: "🇸🇪",
  Sweden: "🇸🇪",
  Norwegia: "🇳🇴",
  Norway: "🇳🇴",
  Dania: "🇩🇰",
  Denmark: "🇩🇰",
  Finlandia: "🇫🇮",
  Finland: "🇫🇮",
  Grecja: "🇬🇷",
  Greece: "🇬🇷",
  Portugalia: "🇵🇹",
  Portugal: "🇵🇹",
  Irlandia: "🇮🇪",
  Ireland: "🇮🇪",
  Kanada: "🇨🇦",
  Canada: "🇨🇦",
  Australia: "🇦🇺",
  "Nowa Zelandia": "🇳🇿",
  "New Zealand": "🇳🇿",
  Japonia: "🇯🇵",
  Japan: "🇯🇵",
  Chiny: "🇨🇳",
  China: "🇨🇳",
  Indie: "🇮🇳",
  India: "🇮🇳",
};

export function getCountryFlag(country: string | null | undefined): string {
  if (!country) {
    return "🌍";
  }

  return COUNTRY_FLAGS[country] ?? "🌍";
}
